base:
  model: "tinycnn"
  epochs: 1
  batch_size: 128
  dataset: "cifar10"
  subset: 256
  num_workers: 0
  seed: 0

grid:
  dropout: [0.0, 0.3]
  lr: [0.003, 0.001]
  wd: [0.0, 0.0005]
  seed: [0, 1]


metric: "val/acc"
goal: "max"
