base:
  model: "tinycnn"
  epochs: 2
  batch_size: 128
  dataset: "cifar10"
  subset: 256
  num_workers: 0
  seed: 0
  run_id: "with_and_without_dropout"

grid:
  dropout: [0.0, 0.3]
  lr: [0.001]
  wd: [0.0]
  seed: [0]


metric: "val/acc"
goal: "max"
