name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10-3.13' }
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
          pre-commit install
      - name: Lint
        run: pre-commit run --all-files
      - name: Tests
        run: pytest -q
